version: 2

sources:
  - name: raw
    schema: gz_raw_data
    description: GreenWeez raw data source
    
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales of GreenWeez / we have one row per products_id found in each orders_id
        tests:
          - unique: 
              column_name: "(orders_id || ' - ' || pdt_id)"
        freshness:
         warn_after: { count: 90, period: day }
        loaded_at_field: "CAST(date_date as TIMESTAMP)"
        columns:
          - name: date_date
            description: date of purchase
          - name: orders_id
            description: unique identifier for an order
          - name: products_id
            description: unique identifier for a product
          - name: revenue
            description: revenue amount of the order
          - name: quantity
            description: quantity number 
   
      - name: product
        identifier: raw_gz_product
        description: This is the raw product data table of GreenWeez
        columns:
          - name: products_id
            description: unique identifier for a product
            tests:
              - unique
              - not_null
              
          - name: purchase_price
            description: cost of purchasing a product

      - name: ship
        identifier: raw_gz_ship
        description: This is the raw shipping data from the source system
        columns:
          - name: orders_id
            description: unique identifier for an order 
            tests: 
              - not_null
              - unique

          - name: shipping_fee
            description: fee revenue from shipping
          - name: logcost
            description: cost logistics relating to the product
          - name: ship_cost
            description: cost of shipping the product
